[package]
name = "pdf_forge"
version = "0.1.0"
edition = "2021"

[lib]
name = "pdf_forge"
path = "src/lib.rs"
crate-type = ["cdylib"] 

[[bin]]
name = "pdf_forge"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.90"
libc = "0.2.161"
pkg-config = "0.3.31"

[build-dependencies]
pkg-config = "0.3"
